### ISSUE TITLE
Order status remains stuck at initialized

### ISSUE THREAD

**Issue by elax46** [MultiSafepay/prestashop-official#6]
Although in the multisafepay console the transaction status is completed, in the back office the transaction remains on MultiSafepay initialized and the transition to the accepted payment status does not take place

**Comment by danielcivit** [comment]
Hi @elax46. 

Thanks for your comment and report.  

I would like to ask if you are sure the application is receiving the HTTP notification from our systems, which updates the order status.  

If you are sure you received the notification, and is not being blocked by a firewall for example, or because the host is not reachable, then you can also look for more information, in the PrestaShop log directory, once you enable debug mode in the MultiSafepay module.

As a third option, please write us an email to support@multisafepay.com (and share with us your merchant ID, and the order number) and we can look internally what is the response from your application to our HTTP notification

**Comment by elax46** [comment]
Fixed the issue that depended on the firewall thanks for the reply
